- rclcpp/test/rclcpp/executors/test_executors.cpp
> rename functions in unit-tests

- rclcpp/include/rclcpp/executor.hpp
- rclcpp/include/rclcpp/executors/events_executor.hpp
- rclcpp/include/rclcpp/executors/timers_manager.hpp
- rclcpp/src/rclcpp/client.cpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/executors/events_executor.cpp
- rclcpp/src/rclcpp/executors/events_executor_entities_collector.cpp
- rclcpp/src/rclcpp/executors/timers_manager.cpp
- rclcpp/src/rclcpp/service.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
- rclcpp/src/rclcpp/subscription_intra_process_base.cpp
- rclcpp/src/rclcpp/waitable.cpp
> fix linter errors

- rclcpp/include/rclcpp/executors/events_executor.hpp
- rclcpp/include/rclcpp/executors/events_executor_entities_collector.hpp
- rclcpp/src/rclcpp/executors/events_executor.cpp
- rclcpp/src/rclcpp/executors/events_executor_entities_collector.cpp
> cleanup entities collector

- rclcpp/src/rclcpp/executors/timers_manager.cpp
- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/executors/test_timers_manager.cpp
> add timers manager test and bug fixes

- rclcpp/include/rclcpp/client.hpp
- rclcpp/include/rclcpp/qos_event.hpp
- rclcpp/src/rclcpp/client.cpp
- rclcpp/src/rclcpp/executors/events_executor.cpp
- rclcpp/src/rclcpp/executors/events_executor_entities_collector.cpp
- rclcpp/src/rclcpp/service.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
- rclcpp/src/rclcpp/subscription_intra_process_base.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
> Revert "void return on set_events_executor_callback"

- rclcpp/include/rclcpp/executors/events_executor_entities_collector.hpp
- rclcpp/src/rclcpp/executors/events_executor.cpp
- rclcpp/src/rclcpp/executors/events_executor_entities_collector.cpp
clean add/remove node APIs and make sure that event callbacks are rem…oved when destroying executor
> clean entities collector

- rclcpp/include/rclcpp/client.hpp
- rclcpp/include/rclcpp/executors/events_executor.hpp
- rclcpp/include/rclcpp/executors/events_executor_entities_collector.hpp
- rclcpp/include/rclcpp/executors/timers_manager.hpp
- rclcpp/include/rclcpp/service.hpp
- rclcpp/include/rclcpp/subscription_base.hpp
- rclcpp/src/rclcpp/executors/events_executor.cpp
- rclcpp/src/rclcpp/executors/events_executor_entities_collector.cpp
- rclcpp/src/rclcpp/executors/timers_manager.cpp
- rclcpp/src/rclcpp/waitable.cpp
- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/executors/test_events_executor.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/executors/test_timers_manager.cpp
> more thread safety and events executor test

- rclcpp/include/rclcpp/executors/events_executor.hpp
- rclcpp/include/rclcpp/executors/events_executor_entities_collector.hpp
- rclcpp/src/rclcpp/executors/events_executor.cpp
> minor cleanup of comments and spin_some timeout

- rclcpp/include/rclcpp/client.hpp
- rclcpp/include/rclcpp/executors/events_executor.hpp
- rclcpp/include/rclcpp/executors/timers_manager.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process_base.hpp
- rclcpp/include/rclcpp/qos_event.hpp
- rclcpp/include/rclcpp/service.hpp
- rclcpp/include/rclcpp/subscription_base.hpp
- rclcpp/include/rclcpp/timer.hpp
- rclcpp/include/rclcpp/waitable.hpp
- rclcpp/src/rclcpp/client.cpp
- rclcpp/src/rclcpp/executors/events_executor.cpp
- rclcpp/src/rclcpp/executors/events_executor_entities_collector.cpp
- rclcpp/src/rclcpp/executors/timers_manager.cpp
- rclcpp/src/rclcpp/service.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
- rclcpp/src/rclcpp/subscription_intra_process_base.cpp
- rclcpp/src/rclcpp/timer.cpp
- rclcpp/src/rclcpp/waitable.cpp
- rclcpp/test/rclcpp/executors/test_events_executor.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
> fix unit tests

- rclcpp/include/rclcpp/executor.hpp
- rclcpp/include/rclcpp/executors/event_waitable.hpp
- rclcpp/include/rclcpp/executors/events_executor.hpp
- rclcpp/include/rclcpp/executors/events_executor_entities_collector.hpp
- rclcpp/src/rclcpp/executors/events_executor.cpp
- rclcpp/src/rclcpp/executors/events_executor_entities_collector.cpp
- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/executors/test_events_executor.cpp
- rclcpp/test/rclcpp/executors/test_events_executor_entities_collector.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/test_add_callback_groups_to_executor.cpp
> add unit tests for callback groups and fix some issues

- rclcpp/include/rclcpp/executors/events_executor.hpp
- rclcpp/include/rclcpp/executors/events_executor_notify_waitable.hpp
> fix comments

- rclcpp/include/rclcpp/executors/events_executor_notify_waitable.hpp
- rclcpp/include/rclcpp/time_source.hpp
- rclcpp/src/rclcpp/client.cpp
- rclcpp/src/rclcpp/executors/events_executor_entities_collector.cpp
- rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
- rclcpp/src/rclcpp/executors/static_single_threaded_executor.cpp
- rclcpp/src/rclcpp/node_interfaces/node_timers.cpp
- rclcpp/src/rclcpp/qos_event.cpp
- rclcpp/src/rclcpp/service.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
- rclcpp/src/rclcpp/subscription_intra_process_base.cpp
- rclcpp/src/rclcpp/time_source.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/test_executor.cpp
I also have merged master so there are some more commits than mine (0efab07)
> Reorder APIs arguments

- rclcpp/src/rclcpp/executors/timers_manager.cpp
- rclcpp/src/rclcpp/timer.cpp
> time_until_trigger return MAX if canceled

- rclcpp/src/rclcpp/qos_event.cpp
- rclcpp/src/rclcpp/subscription_intra_process_base.cpp
> Remove use_previous_event

- rclcpp/include/rclcpp/experimental/buffers/events_queue.hpp
- rclcpp/src/rclcpp/executors/events_executor.cpp
> Unlock queue mutex after taking event

- rclcpp/src/rclcpp/subscription_intra_process_base.cpp
> Do not set gc listener callback

- rclcpp/include/rclcpp/subscription.hpp
Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>
> fix ipc-subscription

- rclcpp/include/rclcpp/executors/events_executor.hpp
- rclcpp/include/rclcpp/experimental/buffers/blocking_concurrent_queue.hpp
- rclcpp/include/rclcpp/experimental/buffers/concurrent_queue/blockingconcurrentqueue.h
- rclcpp/include/rclcpp/experimental/buffers/concurrent_queue/concurrentqueue.h
- rclcpp/include/rclcpp/experimental/buffers/concurrent_queue/lightweightsemaphore.h
- rclcpp/include/rclcpp/experimental/buffers/events_queue.hpp
- rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp
- rclcpp/include/rclcpp/experimental/buffers/simple_events_queue.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
- rclcpp/src/rclcpp/executors/events_executor.cpp
- rclcpp/src/rclcpp/executors/events_executor_entities_collector.cpp
- Add BlockingConcurrentQueue class
- Fix: Calling dequeue on empty ip buffer
> Galactic events executor

- rclcpp/include/rclcpp/experimental/buffers/events_queue.hpp
- rclcpp/include/rclcpp/experimental/buffers/lock_free_events_queue.hpp
- rclcpp/include/rclcpp/experimental/buffers/simple_events_queue.hpp
- rclcpp/src/rclcpp/executors/events_executor.cpp
Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>
> rename lock free queue and remove wait_for_event API

- rclcpp/include/rclcpp/experimental/buffers/events_queue.hpp
- rclcpp/include/rclcpp/experimental/buffers/lock_free_events_queue.hpp
- rclcpp/include/rclcpp/experimental/buffers/simple_events_queue.hpp
- rclcpp/src/rclcpp/executors/events_executor.cpp
Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>
> fix lock free queue

- rclcpp/include/rclcpp/executors/events_executor_entities_collector.hpp
- rclcpp/include/rclcpp/executors/events_executor_notify_waitable.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
- rclcpp/include/rclcpp/qos_event.hpp
- rclcpp/include/rclcpp/waitable.hpp
- rclcpp/src/rclcpp/executors/events_executor.cpp
- rclcpp/src/rclcpp/waitable.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp_action/include/rclcpp_action/client.hpp
- rclcpp_action/include/rclcpp_action/server.hpp
- rclcpp_action/src/client.cpp
- rclcpp_action/src/server.cpp
The Fibonacci actions example works fine. Should be further tested before merge.
> Add support for actions (updated version)

- rclcpp/include/rclcpp/executors/timers_manager.hpp
- rclcpp/include/rclcpp/timer.hpp
- rclcpp/src/rclcpp/executors/events_executor.cpp
- rclcpp/src/rclcpp/executors/timers_manager.cpp
- rclcpp/src/rclcpp/timer.cpp
Signed-off-by: Alberto Soragna <alberto.soragna@gmail.com>
> some updates and fixes to timers manager

- rclcpp/include/rclcpp/client.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process_base.hpp
- rclcpp/include/rclcpp/qos_event.hpp
- rclcpp/include/rclcpp/service.hpp
- rclcpp/include/rclcpp/subscription_base.hpp
- rclcpp/src/rclcpp/client.cpp
- rclcpp/src/rclcpp/executors/events_executor_entities_collector.cpp
- rclcpp/src/rclcpp/publisher_base.cpp
- rclcpp/src/rclcpp/qos_event.cpp
- rclcpp/src/rclcpp/service.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
- rclcpp/src/rclcpp/subscription_intra_process_base.cpp
- rclcpp/src/rclcpp/waitable.cpp
> Unset callback on entities destruction

- rclcpp/include/rclcpp/guard_condition.hpp
- rclcpp/src/rclcpp/guard_condition.cpp
> Add mutex to protect GuardCondition callback

- rclcpp_action/include/rclcpp_action/client.hpp
- rclcpp_action/include/rclcpp_action/server.hpp
- rclcpp_action/src/client.cpp
- rclcpp_action/src/server.cpp
> Action unset callbacks only if they were set

- rclcpp/include/rclcpp/client.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process_base.hpp
- rclcpp/include/rclcpp/qos_event.hpp
- rclcpp/include/rclcpp/service.hpp
- rclcpp/include/rclcpp/subscription_base.hpp
- rclcpp/include/rclcpp/timer.hpp
- rclcpp/src/rclcpp/client.cpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/node_options.cpp
- rclcpp/src/rclcpp/publisher_base.cpp
- rclcpp/src/rclcpp/qos_event.cpp
- rclcpp/src/rclcpp/service.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
- rclcpp/src/rclcpp/subscription_intra_process_base.cpp
- rclcpp/src/rclcpp/time_source.cpp
- rclcpp/src/rclcpp/timer.cpp
- rclcpp/test/rclcpp/test_time_source.cpp
- rclcpp_action/include/rclcpp_action/client.hpp
- rclcpp_action/include/rclcpp_action/server.hpp
- rclcpp_action/src/client.cpp
- rclcpp_action/src/server.cpp
> Temp irobot humble
